name: quidaw
description: "An app that aims to keep Zamboangueños up-to-date on the water level in the city."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  webview_flutter: ^4.9.0
  get: ^4.6.6
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1


flutter:

  uses-material-design: true

  assets:
    - lib/assets/flood_prone_areas.json
    - lib/assets/hotlines.json
    


